badgateway/ketting

- lib/resource.js
- readme.md
Instead of making the Resource thenable, I thought this might be a simpler solution. Making the resource thenable scared me a bit because it had much wider implications.
I think this at least solves the basic problem we ran into... maybe it's enough. This repo desperately needs some unittest but curious to your thoughts @pschwyter.
> Allowing for chained follows by extending the Promise.

- changelog.md
- lib/client.js
- package.json
- test/fixtures/hal-collection.json
- test/fixtures/hal1.json
- test/integration/put.js
- test/integration/request-api.js
- test/testserver.js
These tests will help in making a simple BC layer, which will eventually allow us to complete #11 / #14 in a non-breaking way.
In the process, I also found a bug that caused every instance of Client to
share the instance of its resourceCache. This is now fixed.
> Added lots of request() tests,

- Makefile
- lib/representor/hal.js
- readme.md
- test/integration/follow-hal.js
According to the HAL mailing list, this is actually not how curies are
intended to behave. Curies don't act as XML namespaces, they just
provide a sort of shortcut to related documentation.
> Reverted curie support.

- lib/ketting.js
@enrique-ramirez I tried this in another browser, and got an error related to not initializing an object correctly. I fixed that here
Mind giving this one a shot? Still not 100% sure if this does the trick to you. First time using Object.assign.
> initializing newInit as an object

- lib/ketting.js
- lib/utils/oauth.js
- package-lock.json
- package.json
- readme.md
- test/fixtures/hal1.json
- test/integration/bearer-auth.js
- test/integration/oauth-auth.js
- test/testserver.js
This is work for #19.
@evert,
I've added a new auth type: `oauth2` and support for the owner flow. What I've done so far is to just request the authorization token when it is missing and set it in the ketting object. You can see in the new tests how configuring this works. This makes use of https://github.com/mulesoft/js-client-oauth2 for managing the oauth client.
I still need to add support for refreshing the token and updating the docs, but I'd like to get your initial thoughts.
> Add oauth2 owner flow support

- Makefile
- package-lock.json
- package.json
- webpack.config.js
All tests are now passing in browser.
Fixes #78.
> Added workaround for `querystring.unescape` not working.

- Makefile
- package.json
- tsconfig.json
* No longer allowing non-typescript.
* Automatically publish types.
* No longer publish `.ts` files in npm package.
> Also publish types

- changelog.md
- src/ketting.ts
- src/representor/jsonapi.ts
- test/fixtures/hal1.json
- test/fixtures/json-api.json
- test/integration/follow-jsonapi.ts
- test/integration/get.ts
- test/testserver.ts
- test/unit/representor/jsonapi.ts
This PR adds some support for the JSON:API content-type. This change
will parse the "links" object from the top-level document.
links objects appearing deeper in the document are currently ignored.
I'm hoping this is a good first foundation. From this we might be able
to figure out what the next steps are for dealing with embedded items
and links objects appearing elsewhere in the document.
@gabesullice : mind reviewing this?
Related issues: #109 #111
> Basic JSON:API support.

- src/link.ts
- src/representor/hal.ts
- src/representor/html.ts
- src/representor/html.web.ts
- src/representor/jsonapi.ts
- src/resource.ts
- test/integration/get.ts
- test/unit/link.ts
- test/unit/representor/html.ts
- test/unit/representor/jsonapi.ts
The name 'context' is used in the Web Linking RFC:
https://tools.ietf.org/html/rfc8288#section-3.2
Since we're doing a major release, this is a good time to clean this up. This is a minor BC break.
Fixes #122
> Renaming 'baseUri' to 'context'

- changelog.md
- package.json
- src/resource.ts
- test/fixtures/hal-collection.json
- test/fixtures/hal1.json
- test/integration/get.ts
- test/testserver.ts
This is a first stab at automatically adding:
* [Prefer-Push](https://tools.ietf.org/html/draft-pot-prefer-push)
* [Prefer: transclude](https://github.com/inadarei/draft-prefer-transclude/blob/master/draft-inadarei-prefer-transclude-00.txt)
Both of these drafts solve similar problems. This is gonna be added to the main Ketting library as an experimental feature, to hopefully get some early feedback. This should not impact most users as servers are unlikely to use it right now.
> A simple prefer-push implementation

- src/ketting.ts
- src/resource.ts
- src/utils/fetch-helper.ts
This will make expiring representations behave more predictably.
> Handling cache on a global level.

- src/ketting.ts
- src/link.ts
- src/representor/base.ts
- src/representor/hal.ts
- src/representor/html.ts
- src/representor/html.web.ts
- src/representor/jsonapi.ts
- src/resource.ts
- src/types.ts
- src/utils/fetch-helper.ts
- test/unit/ketting.ts
- test/unit/representor/html.ts
- test/unit/representor/jsonapi.ts
- test/unit/utils/fetch-helper.ts
- tsconfig.json
This PR makes support for new formats easier to add in, and opens the door to a few more features.
The representor system was probably among the oldest bits in ketting, and was from a time where I didn't understand typescript as well as I do now.
This also turns on typescript's `strictNullChecks`, which makes typing much stricter when it comes to initializing things with `undefined` or `null`.
> Rewrite of the representator system.

- src/follower.ts
- src/ketting.ts
- src/resource.ts
* patch() can now be typed.
* If no type is supplied for patch bodies, Partial<X> is assumed for
patch, meaning that we assume that patch bodies will just have a
subset of properties from the PUT request.
* Types can now be provided when linking.
* If using the post() function with type T as the argument, and the
HTTP response to POST includes a location header, the function now
assumes that the resource in this header is of type T, and a
Resource<T> is returned.
> Added a LOT more types everywhere.

- src/ketting.ts
- src/utils/fetch-helper.ts
- src/utils/http.ts
- test/unit/ketting.ts
When a HTTP method returns a Link header that contains a
rel="invalidates", then it means that the HTTP request that was recently
performed has caused other resources to change.
For example, given a resource /article/ that has a list of articles, and
a resource /article/123, running a DELETE request on /article/123 will
also cause a change to the articles list.
If the response to DELETE included the following header:
Link: </article>; rel="invalidates"
Then this can signal a client that the cache for the /article
collection is no longer valid.
The 'invalidates' link relationship is specified in this draft:
https://tools.ietf.org/html/draft-nottingham-linked-cache-inv
> Support the 'invalidates' link.

- src/follower.ts
- src/ketting.ts
- src/resource.ts
```typescript
resource
.followAll('item')
.preFetch();
```
Will cause the GET request for the linked resource to be kicked off
as early as possible, and in parallel.
> Prefetch on .follow()

- src/ketting.ts
- src/representor/helper.ts
- src/resource.ts
- src/types.ts
- test/unit/representor/helper.ts
Centralized a bunch of the 'representor'-related functionality to a
single class. This makes the Resource and Ketting classes a tad easier
to understand.
It's not quite simple enough yet, but it's making headway.
> Refactor representor mapping

- src/follower.ts
- test/unit/follower.ts
I'm adding a default way to ketting to tell the server: "Please add all the link entries from this link relationship as hal _embedded items", creating a compound response.
Usage:
```typescript
const itemResources = await resource.followAll('item').preferTransclude()
```
> Adding an option to send along Prefer: transclude=rel

- src/follower.ts
This ensures that this actually works:
.follow().followAll().preFetch()
> Correct the return type of followAll on FollowerOne.

- src/index.ts
- src/representor/hal.ts
- src/representor/index.ts
- src/resource.ts
I had to export also the RepresentorHelper because the creation of the representor is handled by the create() method of the RepresentorHelper.
> Export representos and RepresentorHelper

- src/follower.ts
Promises in recent javascript engines now have a finally() function, so we need one too if we want to be compatible with them
> finally() implementation for Follower

- readme.md
Hi everyone 👋,
This PR fixes some small issues on the README file and the acronym HATEOAS (Hypermedia as the Engine of Application State).
Thanks!
> docs: fix typos and spacing issue

- src/state/collection-json.ts
- src/state/hal.ts
- src/state/html.ts
- src/state/siren.ts
- test/unit/state/hal.ts
This implements a serializer for HAL.
We're gonna throw exceptions for HTML, Siren and Collection+JSON for now.
I don't have enough real-world experience to make decisions on how this
should be done, or at all. My sense is that these formats are mostly
read-only and instead users should interact with
siren/collection+json/html states through the actions/forms they expose.
So instead we'll leave this open until someone who does have a good idea on how this should be approached comes along. 
Fixes #194
> State serializers

- changelog.md
- src/client.ts
- src/http/util.ts
- src/index.ts
- src/resource.ts
- test/integration/post-follow.ts
- test/unit/resource.ts
Since this PR there are now 2 POST related functions:
1. post() - For RPC operations and form submissions, returns a State
2. postFollow() - For creation of new resources. Returns a new Resource.
Fixes #184
> post() is renamed to postFollow() and new post() functionality for forms 

- src/index.ts
- This will allow ketting users to use `.resolve()` to bypass having to generate a new URL for link association.
> exporting resolve from ketting util

- src/resource.ts
This allows users to update a local cache/state and emit change events
without sending state to the server.
This will be useful for react components that need to make local changes before a `PUT` request.
> Create a new updateState function on Resource

- src/resource.ts
`headers` property passed into `resource.refresh` was not added to the request.
> Fixed headers property in `getOptions`

- src/client.ts
- src/resource.ts
- test/unit/resource.ts
Refresh was recently refactored to use an internal cache updating
function. Unfortunately this caused embedded resources to not be cached.
Fixes #229
> Call the correct cache updating function.

- src/http/fetcher.ts
When "setting" a `User-Agent` header, some browsers will add `user-agent` to `Access-Control-Request-Headers`, which will require API's to allow `user-agent` in their CORS settings, this behaviour should be possible to deactivate.
> Only alter 'User-Agent' if `client.fetcher.advertiseKetting` is true

- src/client.ts
If the mimetype followed the pattern application/anything+json, we'll
just default to HalState. Might make this configurable later, but it's a
reasonable default for now.
> Use HalState as a fallback for other JSON formats.

- src/representor/helper.ts
- test/integration/get.ts
- test/unit/representor/helper.ts
Until HAL Forms is fully implemented in Ketting, this change adds its mime type to HAL representor.
This should not cause any trouble since HAL Forms is backward compatible with HAL.
Please note that adding a custom content type via Ketting options is not enough since we can't give it a `q` value higher than the value `1` assigned to the default `application/hal+json` content type:
```typescript
new Ketting('...', contentTypes: [{
mime: 'application/prs.hal-forms+json',
representor: 'hal',
q: '1.0'
}]);
```
```typescript
const defaultTypes: ContentType[] = [
{
mime: 'application/hal+json',
representor: 'hal',
q: '1.0',
},
// ....
];
```
> Add HAL FORMS to accepted HAL mime types

- .eslintrc.json
- src/action.ts
- src/field.ts
- src/resource.ts
- src/state/base-state.ts
- src/state/hal.ts
- src/state/html.ts
- src/state/interface.ts
- src/state/siren.ts
- test/unit/follower.ts
- test/unit/link.ts
It's greatly simplified but makes more assumptions about the structure
of an action.
Actions are now basically a simple serialization for a HTML form. The
supported formats all fit in this structure, but it's possible that in
the future this is no longer the case.
This makes it possible however to take an action object, and have all
the information available to render a full HTML form.
This is a BC break for actions, but given that actions were still
experimental, I think that's OK. The API behaves mostly the same.
This will be released eventually as 6.1.
@reda-alaoui what do you tihnk?
> Action system rewrite.

- src/resource.ts
This function gives you the current cached state of the resource, and
null if none was available.
The biggest benefit over .get is that it's not async, which will help
with inital stale-while-revalidate operations in react.
> Add a getCache function.

- changelog.md
- src/follow-promise.ts
- test/integration/follow-hal-template.ts
> Templated links don't work if no template variables are supplied.

- package-lock.json
- package.json
- src/http/oauth2.ts
* Ensure that only 1 refresh operation will happen in parallel. If there are multiple things triggering the refresh, all will wait for the first one to finish.
* Automatically schedule a refresh operation 1 minute before the access token expires, if the expiry time is known.
> Update to new fetch-mw-oauth2

- changelog.md
- src/client.ts
- src/middlewares/warning.ts
- src/state/base-state.ts
- test/unit/middleware/warning.ts
Ketting will now emit warnings if it runs into a 'Deprecation' HTTP response header.
> Add support for draft-dalal-deprecation-header.

- src/client.ts
- src/middlewares/cache.ts
> If a Content-Location appears, store the response body in the cache.

- src/util/uri.ts
- src/util/uri.web.ts
- test/unit/state/html.ts
- test/unit/state/siren.ts
Reverts badgateway/ketting#344
This change caused some issues with expanding relative uris on node.js
We might simply need a fallback that supports resolving relative uris
> Revert "Unify the URI utility."

- changelog.md
- src/state/siren.ts
Something in the siren spec caused me to miss a couple of properties on fields in Siren. Got the whole set now i think
> Using field titles in Siren

- src/middlewares/cache.ts
- test/unit/client.ts
See:
https://datatracker.ietf.org/doc/html/draft-nottingham-linked-cache-inv-04#section-4
The 'inv-by' link lets a resource tie its cache status to the cache
status of another resource.
For example, if we have to resources:
```
/foo/1
/foo/1/comments
```
And `/foo/1/comments` returns a `inv-by` link that points to `/foo/1`,
it means that _if_ the cache of `/foo/1/comments` expires for any
reason, the cache for `/foo/1` will also expire.
> Support for the "inv-by" link.

- src/state/hal.ts
- test/unit/state/hal-forms.ts
This replaces #393.
It was pointed out by @reda-alaoui that if a HAL Form is embedded inside
an embedded document, the 'target' attribute (which is a URI) is
resolved with the URI of the main document, not the self link of an
embedded document.
I tried to find a source for what the correct behavior for _any_ link in
an embedded document HAL-Forms or HAL itself is, but there's no guidance.
Intuitively it feels that resources that are serialized are likely
serialized by the same process, whether they are stand-alone or
embedded, so if I had to pick a behavior, it makes more sense to me that
we use the embedded uri.
To my surprise and sadness, it looks like we've never done this for
HAL-Forms inside `_embedded`, but also not `_links` or nested
`_embedded` in `_embedded`.
This PR fixes this …
> HAL: Relative URIs in embedded docs are now resolved with the self link.

- changelog.md
- src/state/hal.ts
> Emit a warning when an _embedded entry without a self link was found.

- src/client.ts
- test/unit/client.ts
Fixes #414.
Many servers will return a `Content-Type` for 204 responses, even though
this is probably incorrect, but at least meaningless.
This fix ensures that we're not attempting to parse the response body
if a 204 is returned.
> Don't error when 204 is returned with a content-type.

- changelog.md
- src/client.ts
- src/middlewares/cache.ts
- src/resource.ts
This is a fix for #416.
All tests pass, so this should not be a breaking change. The Client is
getting more and more 'cache functions'.
I would have preferred these features to exist in the `src/cache`
directory, but doing so would be a BC break so we can only introduce
this in a major version.
> Handling of dependencies in caches is moved to the Client

- src/resource.ts
When Ketting is used in the frontend, we want to encourage it being used as a store for central state. If a piece of data is used in different places, this will usually result in events being registered.
The default of 10 is quite low, and standard applications often start emitting tons of annoying warnings for 'max listeners'. This is annoying and creates distrust. Having a lot of listeners on a single EventEmitter _can_ be indicative of a memory leak, but having lots of listeners itself is not cause for concern.
This PR increases it to 500 for the Resource object. This is plenty of room.
> Increase 'max listeners'.

- src/client.ts
- src/middlewares/cache.ts
- test/unit/client.ts
The `inv-by` link is an incredibly useful tool to automatically let resources expire when other resources expire.
In Ketting it was only possible to communicate this if those links appeared in HTTP Link headers.
This PR ensures that the inv-by link is now also supported in:
* HAL _links
* HAL _links inside HAL _embedded
* Any other format that supports links really
> Support inv-by cache dependencies from HAL bodies

- package-lock.json
- src/state/interface.ts
Maybe there's an even better solution out there, but for now we should steer people away from getEmbedded a bit more.
See: #428 #407 #275 #273
> getEmbedded() should be discouraged

- src/client.ts
- src/resource.ts
This makes following links a tad easier. For example:
```typescript
client.go(
resourceState.links.get('collection')
);
```
Instead of:
```typescript
const link = resourceState.links.get('collection');
client.go(
resolve(link.context, link.href)
);
```
Fixes #328
> Allow Link objects to be passed to the 'go' function.

- src/client.ts
Currently Ketting has a race condition for updates with embedded items.
If items are embedded, we were sending out 'update' events even if the
entire request wasn't processed yet.
This can make it unpredictable to know whether a resource's parent or
child is updated.
This change processes an entire _embedded tree with sub-dependencies,
and only after the entire tree is cached it will start sending out
'update' events.
Now, when you receive an 'update' event the entire cache state is
consistent.
> Only emit 'update' events after the entire state cache has been updated.

- package-lock.json
- package.json
- src/field.ts
- src/state/hal.ts
- test/unit/state/hal-forms.ts
This is the same PR as nodejs/node#439, but applied to the stable version-7.x branch
> Add missing textarea attributes

- src/link.ts
This PR is only a Typing changes to support multiple values with the same key
```js
const templ = uriTemplate.parse("http://localhost:8080/api/contacts{?status}");
const expanded = templ.expand({status: ["valid", "waiting"]});
// http://localhost:8080/api/contacts?status=valid,waiting
```
Resolves #421
> Enable to set multiple values with the same key

- changelog.md
- src/action.ts
If a HTML form has a hidden field, the user doesn't need to do anything with these fields; they just get sent along with requests.
We want HAL forms to work the same way. If a HAL form has hidden fields, we'll just adopt the values (unless overwritten). This has the additional advantage that new hidden fields can be added without changing clients.
This doesn't work for just hidden fields, any form field that has a 'value' will adopt this value unless overridden.
This PR also adds some support for validation. If a form field was 'required', and no value was specified for that field we'll now error.
> Better hidden field support + required validation

- .eslintrc.json
- package-lock.json
- package.json
- src/http/oauth2.ts
This new client has a lot more features. This PR creates a compatibility layer for the old API so nothing changes yet.
In the future the goal is to remove the @badgateway/oauth2-client dependency from ketting and only suggest it. The library itself has a way to create a ketting-compatibile middleware.
> Upgrade from fetch-mw-oauth2 to @badgateway/oauth2-client

- changelog.md
- src/middlewares/cache.ts
- test/unit/resource-events.ts
This solves one of the two problems in #474
> Support `cache: no-store` when calling fetch().

- changelog.md
- src/middlewares/cache.ts
This solves 1 of the 2 issues of #474
> Clone responses before reading when handing`Content-Location`.

- src/field.ts
- src/index.ts
> Export field types
