badgateway/ketting

- lib/resource.js
A simple way to do custom requests, so we can get access to HTTP responses if we need them.
> Accessing a HTTP response.

- changelog.md
- lib/followable-promise.js
- lib/representation.js
- lib/resource.js
- package.json
- readme.md
This PR does not have the ability to cache embedded resources.
> Parsing _embedded and treat the items as link

- readme.md
* opiniated vs. opinionated
* respresentation vs. representation
> docs(readme): correct spelling

- changelog.md
- lib/client.js
- lib/representation.js
- lib/resource.js
- package.json
- readme.md
> Automatically parsing _embedded resources and caching resource objects.

- .gitignore
- .travis.yml
- changelog.md
- lib/client.js
- lib/resource.js
- package.json
- test/bootstrap.js
- test/fixtures/hal-collection.json
- test/fixtures/hal1.json
- test/fixtures/hal2.json
- test/integration/delete.js
- test/integration/follow-hal.js
- test/integration/post.js
- test/integration/put.js
- test/mocha.opts
- test/testserver.js
> Added a basic test framework

- test/fixtures/hal-collection.json
- test/fixtures/hal1.json
- test/integration/get.js
- test/testserver.js
We need to fully test this to make sure everything from #12  / #17 will work correctly.
> Testing if GET requests properly make their way to the server.

- changelog.md
- lib/client.js
- package.json
- readme.md
- test/integration/get.js
> Support for setting a contentType header

- lib/link.js
- lib/representor/hal.js
- lib/representor/html.js
- lib/representor/html.web.js
- lib/resource.js
- test/integration/get.js
- test/unit/representor/html.js
The Link object is getting more and more arguments, so it's time to turn the constructor into an object.
> Switching the Link object to take an object in its constructor.

- lib/representor/hal.js
- test/fixtures/hal1.json
- test/integration/follow-hal.js
> Fixed curie parsing bugs.

- lib/ketting.js
Hi @enrique-ramirez, would you mind taking a look at this and see if this is a good enough solution for you?
Fixes issue #50
> Allow init() settings to be set for the entire library

- lib/ketting.js
- lib/utils/oauth.js
Need to pass the correct object to helper functions and actually set header after fetching access token
> Fix oauth2 not actually working

- lib/resource.js
- test/integration/fetch-api.js
> Fix init on resource fetch not overriding fetchInit on client

- lib/followable-promise.js
- test/integration/follow-hal-template.js
> Fix templated links not working after multiple follows

- changelog.md
- lib/ketting.js
- package.json
- test/integration/get.js
> Support for q= parameters on the Accept header.

- lib/ketting.js
- lib/resource.js
- package-lock.json
- package.json
- test/mocha.opts
This should also improve browser support for more advanced patterns.
Some of this stuff only worked because we used node-fetch.
After this is merged, I'm gonna release a 1.0.0
> Updated all dependencies. Made the fetch stuff work better.

- Makefile
- package-lock.json
- package.json
- test/fixtures/index.html
- test/mocha.opts
- test/test-entrypoint.js
- test/testserver.js
- webpack.config.js
Pretty happy about this one! Fun fact: tests are failing. Will fix this in a different branch.
Fixes: #73
> Tests now run in browsers. Just load up the test server and go!

- changelog.md
- src/utils/fetch.web.js
> Fix for Issue 76

- changelog.md
- src/resource.js
- test/integration/fetch-api.js
> Using mergeHeaders utility in resource.fetch.

- changelog.md
- readme.md
- src/resource.ts
- test/integration/patch.ts
- test/testserver.ts
> Support for resouce.patch().

- readme.md
I really like this project! I've actually been thinking about creating essentially the same thing, so thank you for saving me the trouble!
> Typo fix and general README cleanup

- changelog.md
- package-lock.json
- package.json
- readme.md
- src/ketting.ts
- src/utils/oauth.ts
- test/integration/oauth-auth.ts
- test/testserver.ts
FYI @mhum I'm adding support for another grant_type
> OAuth2 client credentials support

- src/representor/jsonapi.ts
- test/fixtures/json-api.json
- test/integration/follow-jsonapi.ts
Relates to #109 
cc @gabesullice @ethanresnick
> JSON:API collections have 'item' links to their members.

- changelog.md
- src/link.ts
- src/representor/html.ts
- src/resource.ts
- src/utils/oauth.ts
- src/utils/url.ts
- test/testserver.ts
- tsconfig.json
> Support for Typescript environment without esModuleInterop

- Makefile
- package-lock.json
- package.json
- readme.md
- src/utils/oauth.ts
Somehow some changes were not merged in for the 3.0 release. Bit late, but doing this now!
> Fetch mw oauth2

- src/index.ts
> Fix the default export for browser distros and nodejs

- changelog.md
- readme.md
- src/ketting.ts
- src/representor/siren.ts
- test/integration/get.ts
- test/unit/representor/siren.ts
> Support for the Siren format

- src/follower.ts
- src/resource.ts
Adding .preferPush as an option to `.follow()`. This should make preferPush work much better for real-world purposes.
> Prefer-push is opt-in and more reliable

- package-lock.json
- package.json
- src/ketting.ts
- src/utils/fetch-helper.ts
This is a WIP feature and not 100% complete. It's in here now for experimental purposes.
Eventually this will become a non-experimental API.
> Add an options hydrator

- test/unit/follower.ts
- test/unit/resource.ts
Inching closer to 100% coverage
> More tests

- src/representor/hal.ts
- test/unit/representor/hal.ts
> If links appear in both _embedded and _links, deduplicate.

- changelog.md
- src/client.ts
- src/state/hal.ts
- test/unit/client.ts
We're also supporting nested embedded items for the first time.
Fixes #193
Fixes #175
> Embedded resource cache.

- src/util/uri.web.ts
> Passing a relative uri to bookmark fails

- src/cache/forever.ts
- src/cache/index.ts
- src/cache/never.ts
- src/cache/short.ts
- src/index.ts
- test/unit/cache/forever.ts
- test/unit/cache/never.ts
- test/unit/cache/shortcache.ts
> Added a 'short cache'  and 'never cache' implementation.

- changelog.md
- src/resource.ts
> Tell fetch to skip browser cache.

- changelog.md
- src/resource.ts
- src/util/fetch-body-helper.ts
- src/util/fetch-body-helper.web.ts
- src/util/html.web.ts
- test/unit/resource.ts
A few tests were failing in the browser, this PR fixes those
> Fixing browser-side bugs

- src/action.ts
- src/client.ts
- src/state/base-state.ts
- src/state/interface.ts
- src/state/siren.ts
- test/unit/state/siren.ts
This PR allows Siren actions to be executed. The approach is (for now)
rudimentary. Hopefully this will cause some folks to start using this
and provide feedback on how this functionality should be expanded.
> Basic support for Siren actions

- src/action.ts
- src/state/html.ts
- src/state/siren.ts
- src/util/html.ts
- src/util/html.web.ts
- test/unit/state/html.ts
> Submitting HTML forms.

- .eslintrc.json
- changelog.md
- package-lock.json
- package.json
* Updated dependencies
* Updated changelog
* Brougth eslint config up to date
> Prepping for new Beta release.

- src/resource.ts
Return new State object on `patch` if server respond with 200
> Return new State object on `patch` if server respond with 200

- src/state/base-state.ts
Updates, but does not complete #221
> ETag and Last-Modified are content headers.

- src/client.ts
- test/integration/get.ts
> Add HAL FORMS to accepted HAL mime types

- changelog.md
- package-lock.json
- package.json
> Release 6.0.3

- src/client.ts
- src/http/fetcher.ts
- src/middlewares/accept-header.ts
- src/middlewares/cache-expire.ts
Reduces the bulkiness a bit, especially since we're adding more.
> Refactor middlewares into their own directory.

- changelog.md
- package-lock.json
- package.json
- src/field.ts
- src/state/hal.ts
* `target` on forms
* `type`, `min`, `max`, `step`, `minLength`, `maxLength`, `placeholder` on form fields!
> Updating Ketting to use all the latest Hal-forms features

- changelog.md
- package-lock.json
- package.json
- src/field.ts
- src/state/hal.ts
Also add support for a 'textarea' field.
> Update to latest Hal-forms

- src/http/error.ts
- test/unit/error.ts
This will:
* Make the other fields in the problem body easier to access in TypeScript.
* Provide defaults for the type and status fields as defined in RFC-7807.
* Adds unit tests for the error types.
> 332: Improvements to the Problem type.

- src/client.ts
- src/follow-promise.ts
- src/index.ts
- src/resource.ts
- src/state/base-state.ts
- src/state/binary.ts
- src/state/collection-json.ts
- src/state/hal.ts
- src/state/head.ts
- src/state/html.ts
- src/state/index.ts
- src/state/interface.ts
- src/state/jsonapi.ts
- src/state/siren.ts
- src/state/text.ts
- src/util/html.web.ts
- src/util/uri.web.ts
- test/integration/follow-jsonapi.ts
- test/unit/cache/forever.ts
- test/unit/cache/never.ts
- test/unit/cache/shortcache.ts
- test/unit/client.ts
- test/unit/follower.ts
- test/unit/state/collection-json.ts
- test/unit/state/hal.ts
- test/unit/state/html.ts
- test/unit/state/jsonapi.ts
- test/unit/state/siren.ts
This change:
* Reduces some redundant code
* Ensures state.client is statically checked.
* Add '.follow' and '.followAll' to State
Fixes #326
> Another state refactor.

- changelog.md
- src/resource.ts
> Don't ignore browser cache when using .get().

- changelog.md
- src/follow-promise.ts
- test/unit/follower.ts
Background: https://evertpot.com/http-2-push-is-dead
> Remove Prefer-Push functionality.

- changelog.md
- package-lock.json
- package.json
> Remove 'browser' key from package.json
